import { type NextPage } from 'next'
import Head from 'next/head'
import { Input } from '~/components/input'

const GeneratePage: NextPage = () => {
  //   const hello = api.example.hello.useQuery({ text: 'from tRPC' })

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1>Type a prompt to generate</h1>
        <form className='flex flex-col gap-3' action="">
          <label htmlFor="Prompt">Prompt </label>
          <Input></Input>
          <button className="rounded-md bg-blue-500 px-4 py-2 hover:bg-blue-600">Generate </button>
        </form>
      </main>
    </>
  )
}

export default GeneratePage
