import { type NextPage } from 'next'
import Head from 'next/head'

const HelloPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex-col  flex  items-center  bg-gradient-to-b from-[#2e026d] to-[#15162c]"></main>
    </>
  )
}

export default HelloPage
